object Fields {
  val id = "_id"
  val userName = "userName"
  val password = "password"
  val name = "name"
  val favouriteThemes = "favouriteThemes"
  val messages = "messages"
  val friends = "friends"
  val subscribers = "subscribers"
  val favouriteMessages = "favouriteMessages"
  val timeline = "timeline"
  val text = "text"
  val owner = "owner"
  val theme = "theme"
  val comments  = "comments"
  val references = "references"
  val likes = "likes"
  val usersWhoReacted = "userWhoReacted"
  val dislikes = "dislikes"
  val rating = "rating"
  val database = "mydb"
  val collection = "test"
  val path = "path"
  val ownerOfMessage = "ownerOfMessage"
}

